export const SET_CATEGORY='SET_CATEGORY'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT='LOGOUT';
export const AGREEMENT='AGREEMENT';
export const UPLOAD_COMPLETE='UPLOAD_COMPLETE';